import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { privateKeyToAccount, generatePrivateKey } from 'viem/accounts';
import { keccak256, concatHex } from 'viem';
const vars = Object.fromEntries(readFileSync('.dev.vars', 'utf8').trim().split('\n').map(l => { const i=l.indexOf('='); return [l.slice(0,i),l.slice(i+1)]; }));
const root = privateKeyToAccount(vars.AGENT_PRIVATE_KEY);
const wallet = privateKeyToAccount(generatePrivateKey());
const base = 'http://127.0.0.1:8897';
const api = (path, body, token) => fetch(base+path, { method: body === undefined ? 'GET':'POST', headers: { 'content-type':'application/json', ...(token ? {authorization:`Bearer ${token}`} : {}) }, ...(body === undefined ? {} : {body:JSON.stringify(body)}) });
const empty = {mandates:[],positions:[],activity:[],prices:[],orders:[],pipelineTests:[]};
const snapshot = {rootAddress:root.address,database:empty,mode:{live:false},chats:{messages:[]},usage:{day:'',total:0,owners:{}},credentials:{}};
assert.equal((await api('/')).status,503);
assert.equal((await api('/_migration/import',snapshot)).status,404);
assert.equal((await api('/_migration/import',{...snapshot,rootAddress:wallet.address},vars.MIGRATION_TOKEN)).status,400);
assert.equal((await api('/')).status,503);
assert.equal((await api('/_migration/import',snapshot,vars.MIGRATION_TOKEN)).status,200);
assert.equal((await api('/_migration/import',snapshot,vars.MIGRATION_TOKEN)).status,409);
assert.equal((await api('/')).status,200);
assert.equal((await api('/mandates')).status,401);
assert.equal((await api('/mode',{live:true})).status,401);
const challenge = await (await api('/auth/challenge',{account:wallet.address})).json();
assert.ok(challenge.nonce, JSON.stringify(challenge));
const signature = await wallet.signMessage({message:challenge.message});
const response = await api('/auth/verify',{nonce:challenge.nonce,signature});
assert.equal(response.status,200,await response.clone().text());
const session = await response.json();
assert.equal((await api('/auth/verify',{nonce:challenge.nonce,signature})).status,401);
assert.equal((await api('/auth/session',undefined,session.token)).status,200);
const agent = await (await api('/agent',undefined,session.token)).json();
assert.equal(agent.spender.toLowerCase(),privateKeyToAccount(keccak256(concatHex([vars.AGENT_PRIVATE_KEY,wallet.address.toLowerCase()]))).address.toLowerCase());
assert.equal(agent.dryRun,true);
assert.equal((await api('/mode',{live:true},session.token)).status,403);
assert.equal((await api('/demo/mandate-build13-demo.mp4')).status,200);
const nextChallenge = await (await api('/auth/challenge',{account:wallet.address})).json();
writeFileSync('.wrangler/test-session.json',JSON.stringify({session,challenge:nextChallenge,signature:await wallet.signMessage({message:nextChallenge.message})}),{mode:0o600});
console.log('PASS: guarded import, key identity, auth/ownership, nonce replay, static video. Restart the local worker for the persistence check.');
